baseURL = 'https://cornerboxes.com/'
languageCode = 'en-us'
title = "cornerboxes"
theme = 'PaperModX-nordish'
paginate = 10

[params]
env = "production"
defaultTheme = 'auto'
showtoc = true
tocopen = true
ShowBreadCrumbs = true
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
TocSide = 'right'
mainSections = ["projects", "thoughtbooks", "misc"]
author = "Harvey Lim"
ShowAuthor = true
EnableImageZoom = true

[params.homeInfoParams]
Title = 'Welcome ðŸ‘‹'
Content = """Hi! I'm Harvey Lim, a **3rd-year student at Aalto University**. I also go by "rv" or "shzhe02" online.

This website is for documenting my personal projects and general blogging.

Hope you find something interesting!
"""

[[params.socialIcons]]
name = 'github-simple'
url = 'https://github.com/shzhe02'

[[params.socialIcons]]
name = 'linkedin-simple'
url = 'https://www.linkedin.com/in/shzhe02/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[languages.en.menu.main]]
name = "Thoughtbooks"
url = "/thoughtbooks/"
weight = 3

[[languages.en.menu.main]]
name = "Misc"
url = "/misc/"
weight = 4

[[languages.en.menu.main]]
name = "Archive"
url = "/archives/"
weight = 28

[[languages.en.menu.main]]
name = "Search"
url = "/search/"
weight = 29

[[languages.en.menu.main]]
name = "About"
url = "/about/"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]
